// paytrackSchema.js
// -------------------------------------------------------------------
// AUTO-GENERATED by schemamap.js from app\paytrack\schemamap.txt — do not hand-edit
// the globalRelations object below. Edit the spec file and rerun:
//   node schemamap.js
//
// Column name on a specific module differs from the relation key (e.g.
// a polymorphic "__" key, or a renamed FK column) — pass 'key' in
// overrides so both sides stay in sync.
// Override ANYTHING else per-module the same way — second arg always
// wins, shallow merge over the global default.
// Unknown relation key throws instead of silently returning undefined
// (fail loud, not silent).
//
// endpoint (frontend only) resolves live via apiRoutes.json/getApiRoutes,
// keyed by table.replace(/_/g, '') — the SAME default routeKey db-cli.js
// writes when it builds that table's own schema.js. If that table's
// schema was built with a custom --list-name prefix, its real
// apiRoutes.json key won't match this guess — hand-fix that one entry's
// endpoint here (or re-point it at a literal string) rather than
// regenerating; schemamap.js has no way to know about a prefix chosen in
// a different tool's run.
// -------------------------------------------------------------------

export const globalRelations = {

  assigned_to: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: exceptions
  },

  branch_id: {
    table: "branches",
    valueField: "record_id",
    displayField: "branch_name",
    cacheField: "branch_name",
    label: "Branch",
    // used by: business_events, exceptions, integrations, payment_transactions, users
  },

  bundle_id: {
    table: "system_role_bundles",
    valueField: "record_id",
    displayField: "bundle_name",
    cacheField: "bundle_name",
    label: "Bundle",
    // used by: user_bundle_role_functions
  },

  client_id: {
    table: "clients",
    valueField: "record_id",
    displayField: "client_name",
    cacheField: "client_name",
    label: "Client",
    // used by: business_events
  },

  created_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_message_templates, smart_payment_requests, smart_payment_settings
  },

  event_id: {
    table: "business_events",
    valueField: "record_id",
    displayField: "event_id",
    cacheField: "event_id",
    label: "Event",
    // used by: exceptions, payment_matches, reconciliations
  },

  initiated_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_calls
  },

  integration_id: {
    table: "integrations",
    valueField: "record_id",
    displayField: "integration_name",
    cacheField: "integration_name",
    label: "Integration",
    // used by: business_events, imports
  },

  last_updated_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_message_templates, smart_payment_settings
  },

  matched_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: payment_matches
  },

  module_id: {
    table: "system_modules",
    valueField: "record_id",
    displayField: "module_name",
    cacheField: "module_name",
    label: "Module",
    // used by: system_role_permissions
  },

  payment_source_id: {
    table: "payment_sources",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "Source",
    // used by: payment_transactions
  },

  payment_transaction_id: {
    table: "payment_transactions",
    valueField: "record_id",
    displayField: "transaction_id",
    cacheField: "transaction_id",
    label: "Transaction",
    // used by: exceptions, payment_matches
  },

  processed_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_payments
  },

  reconciled_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: reconciliations
  },

  related_record_id__clients: {
    table: "clients",
    valueField: "record_id",
    displayField: "client_name",
    cacheField: "client_name",
    label: "Client",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: smart_calls, smart_messages
  },

  related_record_id__smart_payments: {
    table: "smart_payments",
    valueField: "record_id",
    displayField: "payment_reference",
    cacheField: "payment_reference",
    label: "Payment",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: smart_payment_requests
  },

  related_record_id__system_modules: {
    table: "system_modules",
    valueField: "record_id",
    displayField: "module_name",
    cacheField: "module_name",
    label: "Module",
    // polymorphic "related_record_id" — see other __ variants for its other targets
    // used by: mosy_reminders
  },

  reminder_id: {
    table: "mosy_reminders",
    valueField: "record_id",
    displayField: "reminder_id",
    cacheField: "reminder_id",
    label: "Reminder",
    // used by: mosy_reminder_log
  },

  request_reference: {
    table: "smart_payment_requests",
    valueField: "request_reference",
    displayField: "request_title",
    cacheField: "request_title",
    label: "Request",
    // used by: smart_payments
  },

  resolved_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: exceptions
  },

  role_id: {
    table: "system_roles",
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // used by: system_role_permissions, user_bundle_role_functions, user_manifest_
  },

  sent_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: smart_messages
  },

  uploaded_by: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: imports
  },

  user_id: {
    table: "system_users",
    valueField: "record_id",
    displayField: "name",
    cacheField: "name",
    label: "User",
    // used by: audit_logs, user_manifest_
  },

  user_role: {
    table: "system_roles",
    valueField: "record_id",
    displayField: "role_name",
    cacheField: "role_name",
    label: "Role",
    // used by: system_users
  },

};

function cacheKeyFor(rel, columnKey) {
  return `_${rel.table}_${rel.cacheField}_${columnKey}`;
}

function getRelation(relationKey, fnName) {
  const rel = globalRelations[relationKey];
  if (!rel) {
    throw new Error(
      `${fnName}: no globalRelations entry for "${relationKey}". ` +
      `Regenerate from schemamap.txt, or define this field/join locally instead.`
    );
  }
  return rel;
}

// Use it on the BACKEND schema (in 'batchMutations:'):
//     ...resolveJoin('staff_id')
//     ...resolveJoin('related_record_id__app_users', { key: 'related_record_id' })
//
// Cache alias too long/ugly (e.g. "_fuel_stations_station_name_fuel_station_id")?
// Override it with 'as' — pass the SAME 'as' value to resolveField on the
// frontend side so the two stay pointed at the same column on the row:
//     ...resolveJoin('fuel_station_id', { as: 'station_name' })
export function resolveJoin(relationKey, overrides = {}) {
  const rel = getRelation(relationKey, 'resolveJoin');
  const columnKey = overrides.key || relationKey;
  const cacheKey = overrides.as || cacheKeyFor(rel, columnKey);
  const descriptor = {
    type: 'join',
    table: rel.table,
    link: `${columnKey}:${rel.valueField}`,
    select: { [cacheKey]: rel.cacheField },
  };
  const { key: _unusedKey, as: _unusedAs, ...restOverrides } = overrides;
  return { [cacheKey]: { ...descriptor, ...restOverrides } };
}

// ---------------------------------------------------------------------
// Detected "reverse" relations (record_id referenced FROM another table).
// These are candidate multiGridRows / child-grid wiring, NOT parent
// lookups, so they are not turned into resolveField/resolveJoin entries.
// Wire manually into multiGridRows on the parent module's schema.js.
// ---------------------------------------------------------------------
// (none detected in this spec)
