// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

export const MerchantsSchema = {
  entity: 'merchants',

  moduleRole: 'view_merchants',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'merchant_name', type: 'text', title: true, searchable: true },
    { key: 'contact', type: 'text', searchable: true },
    { key: 'location', type: 'text', searchable: true },
    { key: 'industry', type: 'text', searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'logo', type: 'image' },
    { key: 'row_count', type: 'number', computed: true, editable: false },
    { key: 'total_branches', type: 'number', computed: true, editable: false },
    { key: 'total_transacted', type: 'money', computed: true, editable: false },
    { key: 'total_charges', type: 'money', computed: true, editable: false },
    { key: 'total_disbursed', type: 'money', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // merchants has no direct FK to branches/payment_transactions — both
    // share the same hive_site_id, so that's the link column on both sides.
    total_branches: {
      type: "count", table: "branches", link: "hive_site_id:hive_site_id",
    },
    total_transacted: {
      type: "sum", table: "payment_transactions", column: "amount", link: "hive_site_id:hive_site_id",
    },
    total_charges: {
      type: "sum", table: "payment_transactions", column: "rate_amount", link: "hive_site_id:hive_site_id",
    },
    total_disbursed: {
      type: "sum", table: "payment_transactions", column: "disbursed", link: "hive_site_id:hive_site_id",
    },
  },

  roles: { view: 'view_merchants', manage: 'manage_merchants' },
};
