// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

export const BranchesSchema = {
  entity: 'branches',

  moduleRole: 'view_branches',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'created_at', type: 'datetime', system: true, editable: false },
    { key: 'branch_code', type: 'text', title: true, searchable: true },
    { key: 'branch_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'location', type: 'text', searchable: true },
    { key: 'phone', type: 'text', searchable: true },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/paytrack/branches/list', groupByField: 'status', searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'transaction_rate_cash', type: 'groupedSelect', endpoint: '/api/paytrack/branches/list', groupByField: 'transaction_rate_cash' },
    { key: 'transaction_rate_card', type: 'groupedSelect', endpoint: '/api/paytrack/branches/list', groupByField: 'transaction_rate_card' },
    { key: 'transaction_rate_mpesa', type: 'groupedSelect', endpoint: '/api/paytrack/branches/list', groupByField: 'transaction_rate_mpesa' },
    { key: 'default_transaction_rate', type: 'groupedSelect', endpoint: '/api/paytrack/branches/list', groupByField: 'default_transaction_rate' },
    { key: 'row_count', type: 'number', computed: true, editable: false },
    { key: 'total_paid', type: 'money', computed: true, editable: false },
    { key: 'total_charges', type: 'money', computed: true, editable: false },
    { key: 'total_disbursed', type: 'money', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // payment_transactions.branch_id is a real FK to branches.record_id.
    total_paid: {
      type: "sum", table: "payment_transactions", column: "amount", link: "branch_id:record_id",
    },
    total_charges: {
      type: "sum", table: "payment_transactions", column: "rate_amount", link: "branch_id:record_id",
    },
    total_disbursed: {
      type: "sum", table: "payment_transactions", column: "disbursed", link: "branch_id:record_id",
    },
  },

  roles: { view: 'view_branches', manage: 'manage_branches' },
};
