// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

import { resolveJoin } from '../../paytrackSchema';

export const BybranchMoneyflowSchema = {
  entity: 'payment_transactions',

  moduleRole: 'view_payment_transactions',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'branch_id', type: 'text', searchable: true },
    { key: 'payment_source_id', type: 'text', searchable: true },
    { key: 'transaction_id', type: 'text', searchable: true },
    { key: 'external_ref', type: 'text', searchable: true },
    { key: 'amount', type: 'money' },
    { key: 'currency', type: 'text', searchable: true },
    { key: 'payer_name', type: 'text', title: true, searchable: true },
    { key: 'payer_phone', type: 'text', searchable: true },
    { key: 'payment_mode', type: 'text', searchable: true },
    { key: 'transaction_at', type: 'datetime' },
    { key: 'received_at', type: 'datetime' },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/paytrack/moneyflow/bybranch', groupByField: 'status', searchable: true },
    { key: 'metadata', type: 'textarea', searchable: true },
    { key: 'raw_payload', type: 'textarea', searchable: true },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'rate', type: 'text', searchable: true },
    { key: 'rate_amount', type: 'money' },
    { key: 'disbursed', type: 'text', searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    ...resolveJoin('branch_id', { as: 'branch_name' }),
    ...resolveJoin('payment_source_id', { as: 'name' }),
  },

  roles: { view: 'view_moneyflow', manage: 'manage_moneyflow' },
};
